refactored Post Entity to Content Entity
peterliapin/onlinesales.core pull request #126
Opened 2023-02-21 05:54 UTC by idchrono

refactored Post Entity to Content Entity
Content property of Post renamed to Body
Content property of Comment renamed to Body

test data corrected for new property names
tests: passed

2023-02-26 04:09 UTC, peterliapin requested changes

2023-02-26 04:09 UTC, peterliapin commented on src/OnlineSales/Entities/Content.cs
> +    public string Template { get; set; } = string.Empty;
Please rename Template -> Type

2023-02-27 06:06 UTC, idchrono commented on src/OnlineSales/Controllers/ContentsController.cs
> +public class ContentsController : BaseControllerWithImport<Content, ContentCreateDto, ContentUpdateDto, ContentDetailsDto, ContentImportDto>
fixed

2023-02-27 06:06 UTC, idchrono commented on src/OnlineSales/Data/PgDbContext.cs
> +    public virtual DbSet<Content>? Contents { get; set; }
fixed

2023-02-27 06:55 UTC, idchrono commented on src/OnlineSales/Entities/Content.cs
> +    public string Template { get; set; } = string.Empty;
in process

2023-02-27 07:26 UTC, idchrono commented on src/OnlineSales/Entities/Content.cs
> +    public string Template { get; set; } = string.Empty;
fixed

2023-02-27 08:06 UTC, merged