YARP Plugin. AzureAD Plugin improvements
peterliapin/onlinesales.core pull request #132
Opened 2023-03-03 00:43 UTC by Exmirai

2023-03-06 04:39 UTC, idchrono commented on plugins/OnlineSales.Plugin.AzureAD/AzureADPlugin.cs
> +        services.AddAuthentication("ApiAppAuthorization")
move authentification code to separate file

2023-03-06 04:40 UTC, idchrono commented on plugins/OnlineSales.Plugin.AzureAD/Controllers/AuthController.cs
> +    public async Task Login(string redirectUrl)
describe possible responses for swagger

2023-03-06 04:42 UTC, idchrono commented on plugins/OnlineSales.Plugin.ReverseProxy/ReverseProxyPlugin.cs
> +                policy.RequireAuthenticatedUser().AddAuthenticationSchemes("ApiAppAuthorization"));
you use "ApiAppAuthorization" freqrently enough to move it to constant

2023-03-06 04:44 UTC, idchrono requested changes
check comments above

2023-03-07 05:37 UTC, idchrono requested changes
check comments above

2023-03-07 05:37 UTC, idchrono commented on plugins/OnlineSales.Plugin.AzureAD/AzureADPlugin.cs
> +public class JwtBearerEventsHandler : JwtBearerEvents
move "JwtBearEventHandler" out to separate file

2023-03-07 05:37 UTC, idchrono commented on tests/OnlineSales.Tests/Environment/TestApplication.cs
> +            services.AddAuthentication(defaultScheme: "WebApiAuthorization")
make constant "WebApiAuthorization"

2023-03-10 04:56 UTC, idchrono requested changes
see comments above

2023-03-10 04:56 UTC, idchrono commented on plugins/OnlineSales.Plugin.AzureAD/AzureADPlugin.cs
> +                if (!string.IsNullOrEmpty(administratorsGroupId))
please change to if null throw exception

2023-03-10 12:28 UTC, idchrono approved these changes

2023-03-10 15:28 UTC, peterliapin commented on plugins/OnlineSales.Plugin.AzureAD/AzureADPlugin.cs
>          options.AddSecurityDefinition("Bearer", new OpenApiSecurityScheme()
@Exmirai new cookie based authentication should also be supported in swagger UI. Add it here.

2023-03-10 19:53 UTC, merged