Moved query related things to QueryFactory. Improved SyncEmailLogTask
peterliapin/onlinesales.core pull request #187
Opened 2023-05-22 07:44 UTC by Exmirai

2023-05-22 11:16 UTC, IgorKostyukov requested changes

2023-05-22 11:48 UTC, IgorKostyukov approved these changes

2023-05-23 06:33 UTC, peterliapin requested changes

2023-05-23 06:33 UTC, peterliapin commented on src/OnlineSales/Tasks/SyncEmailLogTask.cs
> +                            contact = contactService.SaveAsync(new Contact
@Exmirai .Result.Entity will be the same instance of the object which you constructed yourselves and passed to SaveAsync. What is the reason for the complexity you introduced with the returning of EntityEntry from the SaveAsync method? Please create and object first and save it into a local variable and than use that variable where needed. There is no need to return EntityEntry.

2023-05-23 07:52 UTC, Exmirai commented on src/OnlineSales/Tasks/SyncEmailLogTask.cs
> +                using (var scope = provider.CreateScope())
because ContactService is transient and tasks are singletons

2023-05-23 10:48 UTC, merged