Fix default language for email templates
peterliapin/onlinesales.core pull request #194
Opened 2023-05-30 19:35 UTC by Mixer57

Added section 'DefaultLanguage' into AppSettings.json with Language property with default value as 'ru-RU'.
Added method GetEmailTemplateByLanguage into EmailFromTemplateService to search template with provided or default language.

2023-05-30 21:07 UTC, peterliapin requested changes

2023-05-30 21:07 UTC, peterliapin commented on src/OnlineSales/Configuration/AppSettings.cs
> +public class DefaultLanguage
@Mixer57 please move it into the existing ApiSettings section.

2023-05-30 21:07 UTC, peterliapin commented on src/OnlineSales/Configuration/AppSettings.cs
> +    public string Language { get; set; } = "ru-RU";
@Mixer57 the default language should be en-US.

2023-05-30 21:07 UTC, peterliapin commented on src/OnlineSales/Services/EmailFromTemplateService.cs
> +using static Org.BouncyCastle.Math.EC.ECCurve;
@Mixer57 why do you need it?

2023-05-30 21:07 UTC, peterliapin commented on src/OnlineSales/appsettings.json
> +  "Plugins": [ "OnlineSales.Plugin.ReverseProxy", "OnlineSales.Plugin.EmailSync", "OnlineSales.Plugin.XLTools" ],
@Mixer57 external plugins should never be included into the core configuration by default!

2023-05-30 21:07 UTC, peterliapin commented on src/OnlineSales/Services/EmailFromTemplateService.cs
> +            var template = await pgDbContext.EmailTemplates!.FirstOrDefaultAsync(x => x.Name == name && (x.Language.Length == 2 ? x.Language == language.Substring(0, 2) : x.Language == language));
@Mixer57 x.Language.Length should never be 2 letters, always 5. If it is not the case we need to fix it on the database level now.

2023-05-31 09:16 UTC, peterliapin requested changes

2023-05-31 09:16 UTC, peterliapin commented on src/OnlineSales/appsettings.json
> +    "Language": "en-US"
Please rename to DefaultLanguage

2023-05-31 09:16 UTC, peterliapin commented on src/OnlineSales/Configuration/AppSettings.cs
> +    public string Language { get; set; } = "ru-RU";
The default should be en-US

2023-05-31 14:54 UTC, Mixer57 commented on src/OnlineSales/Services/EmailFromTemplateService.cs
> +            var settings = configuration.GetSection("ApiSettings").Get<ApiSettingsConfig>();
IOptions<ApiSettingsConfig> apiSettingsConfig used instead configuration.GetSection("ApiSettings").Get<ApiSettingsConfig>();

2023-05-31 14:55 UTC, Mixer57 commented on src/OnlineSales/appsettings.json
> +    "Language": "en-US"
Renamed

2023-06-01 11:33 UTC, merged